version: 2.1

orbs:
  node: circleci/node@4.4.4

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
          working-directory: "~"
      - run: yarn build
      - run: yarn test

  lint:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
          working-directory: "~"
      - run: yarn lint

workflows:
  build_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - build
